### ISSUE TITLE
odd hover effect on sign up button and visited link color misuse 

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/StackOverflow-Dark#93] opened 2017-11-10 12:27 UTC
So this issue has three components comparing the unstyled vs styled.

The first issue is the contrast of the logo on the left, the styled dark version is hardly readable.

The second issue is that the visited link color is being applied to the icon ![capture](https://user-images.githubusercontent.com/31389848/32658433-e52b8a76-c611-11e7-90c0-21793660d262.PNG)
```html
<path d="M1 13c0 1.1.9 2 2 2h8v3l3-3h1a2 2 0 0 0 2-2v-2H1v2zM15 1H3a2 2 0 0 0-2 2v2h16V3a2 2 0 0 0-2-2zM1 6h16v4H1V6z"></path>
```
The unsyled version doesnt apply this decoration or doesnt seem to.

The third issue is how the hover animation on the sign up button + misuse of the visited color combination is really funky and not in a good way :)  when comparing to the actual unstyled version the animation on hover is much more consistent and doesnt use any visited link color.  

![navigation](https://user-images.githubusercontent.com/31389848/32658575-88270214-c612-11e7-882c-88e535524215.gif)

**Comment by tambry** [comment] 2017-11-10 13:10
Unable to reproduce. Make sure your style is up-to-date (using [Stylus](https://add0n.com/stylus.html) is recommended, as it keeps your styles up-to-date) and doesn't conflict with other styles or add-ons. If the issue persists, please provide more specific production steps (ie. exact page).

**Comment by the-j0k3r** [comment] 2017-11-10 16:11
Everything is fully up to date and Im using stylus, https://stackoverflow.com/ link there.

**Comment by tambry** [comment] 2017-11-10 16:30
Can reproduce now. The problem is caused by the non-default "Visited link colour". Since the style currently [sets all links to a certain colour](https://github.com/StylishThemes/StackOverflow-Dark/blob/master/stackoverflow-dark.css#L548) and because technically the buttons are links causes them to be coloured as the visited link colour.  
Note that this is something that causes inconsistencies *everywhere* on the site, especially if you aren't using the default link colour. This is something I've personally wanted to fix, but at this point I'd rather re-write the style completely, but I'm kinda blocked on [this](https://github.com/openstyles/stylus/issues/86), which itself is blocked on [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=732457) (which you should totally upvote 😄).

**Comment by the-j0k3r** [comment] 2017-11-10 16:35
I did say the visited link color was being misused but still doesnt explain the rest of the issues.

**Comment by tambry** [comment] 2017-11-10 16:49
@the-j0k3r No need to write a comment 👍 'ing something. GitHub has the "reactions" feature for that. Although there's no real need to do that on the GitHub issue, as that's something I can easily implement myself - [the Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=732457) is quite a bit harder for me to implement.

**Comment by tambry** [comment] 2017-11-10 16:55
The real problem is that our visited link styling is too broad right now. SO's own visited link colouring uses a much more strict selector. I'll see if I can fix this by using SO's own selector.

**Comment by the-j0k3r** [comment] 2017-11-10 17:03
Would you like me to report the other issues separately? as far as I can see this is uo to 5 issues in this ticket

**Comment by tambry** [comment] 2017-11-10 17:29
I've pushed a fix onto master for the visited links.

@the-j0k3r Please do report the problems that still exist after the fix I just pushed. Note you'll need to manually install the style for now, as releasing it through userstyles.org will take a little while. Thank you for taking time to report the problems!  
Though I'd also recommend that you delete [the comment](https://github.com/openstyles/stylus/issues/86#issuecomment-343521369) you made on one of the issues I mentioned.

I also unfortunately messed up and created an extra merge commit on top of master. It might make sense to rewrite history to remove it, but I don't have force push permissions, so I can't do that.

**Closed by tambry** 2017-11-10 17:29 UTC

**Comment by Mottie** [comment] 2017-11-10 17:34
I'm out of town right now... maybe @silverwind can update USO or it'll have
to wait until next weekend.

**Comment by silverwind** [comment] 2017-11-15 21:12
I release v2.10.23. Also, I added some linting and the `grunt {patch,minor,major}` tasks for easier releasing.
