### ISSUE TITLE
Code parts barely readable

### ISSUE THREAD

**Issue by Maurin3** [StylishThemes/StackOverflow-Dark#221] opened 2020-11-05 17:22 UTC
* **Browser**: Chrome (Version 86.0.4240.183)
* **Operating System**: Windows 10 (1903)
* **Link to page with the issue**: https://stackoverflow.com/questions/64700265/odoo-13-creating-invoice-from-purchase-order-in-odoo-via-api
* **Screenshot**:
![image](https://user-images.githubusercontent.com/28402592/98272724-b017c980-1f91-11eb-8799-c67d103d87d2.png)
As you can see here, most of the code is barely readable.

Here is a screenshot with the HTML and CSS rules : 
![image](https://user-images.githubusercontent.com/28402592/98273326-6a0f3580-1f92-11eb-97fb-6c47049c5a57.png)

And if I uncheck the CSS rule (red circled), it becomes readable again : 
![image](https://user-images.githubusercontent.com/28402592/98273492-9fb41e80-1f92-11eb-8f3e-da9dc78adbcd.png)

The CSS rule is on `pre.s-code-block` if you have a hard time to read on the screenshot.

**Comment by the-j0k3r** [comment] 2020-11-05 17:59
This is a duplicate of issue https://github.com/StylishThemes/StackOverflow-Dark/issues/218

Read NOtes on https://github.com/StylishThemes/StackOverflow-Dark#notes and install https://raw.githubusercontent.com/StylishThemes/Feature-Override-Styles/master/stackoverflow-syntax-themes.user.css

**Closed by the-j0k3r** 2020-11-05 17:59 UTC
Labels: bug :bug:

**Comment by Maurin3** [comment] 2020-11-05 18:08
Ok, Guess I didn't read long enough the README file. Thanks for the explanation.
